import images from "@/lib/images";
import {
  Target,
  MessageCircle,
  Zap,
  Users,
  Award,
  Star,
} from "lucide-react";

export const platforms = [
  {
    icon: <Target className="w-6 h-6 text-accent" />,
    title: "Executive Leadership Conference",
    description:
      "High-level discussions led by industry leaders on the most critical issues shaping Africa's hospitality future.",
    imagePath: images.projectRoundtables,
    label: "Session 1",
    detailsLabel: "Key Sessions",
    ctaLabel: "Register to attend",
    details: [
      "The Future of Hospitality Leadership in Africa",
      "Investment Opportunities in Africa's Hotel Sector",
      "Building Sustainable and Responsible Hospitality Brands",
      "Leveraging Technology to Enhance Guest Experience",
      "Revenue Growth Strategies for Hotel Leaders",
      "Talent Development and Leadership in Hospitality",
      "Africa's Emerging Tourism Destinations",
    ],
  },
  {
    icon: <MessageCircle className="w-6 h-6 text-accent" />,
    title: "CEO & General Managers Roundtable",
    description:
      "An exclusive roundtable session bringing together leading hotel general managers and senior hospitality executives to discuss operational leadership, strategy, and the future of hotel management in Africa.",
    imagePath: images.projectVirtual,
    label: "Session 2",
    detailsLabel: "What to Expect",
    ctaLabel: "Register to attend",
    details: [
      "Exclusive session for hotel GMs and senior executives",
      "Operational leadership and hotel management strategy",
      "Future of hotel management in Africa",
      "Peer-to-peer insights and best practices",
    ],
  },
  {
    icon: <Zap className="w-6 h-6 text-accent" />,
    title: "Hospitality Investment Dialogue",
    description:
      "A special session connecting hotel developers, investors, and hospitality brands to explore new development opportunities across Africa's emerging tourism markets.",
    imagePath: images.projectAI,
    label: "Session 3",
    detailsLabel: "Dialogue Focus",
    ctaLabel: "Register to attend",
    details: [
      "Connecting investors with hospitality brands and owners",
      "New hotel development opportunities across Africa",
      "Emerging tourism market insights and strategy",
      "Asset management and hotel investment approaches",
    ],
  },
  {
    icon: <Users className="w-6 h-6 text-accent" />,
    title: "Executive Networking Reception",
    description:
      "A high-level networking platform where industry leaders can connect, build partnerships, and explore collaborations across Africa's hospitality ecosystem.",
    imagePath: images.projectMobility,
    label: "Session 4",
    detailsLabel: "Networking Highlights",
    ctaLabel: "Register to attend",
    details: [
      "Curated networking with Africa's top hospitality leaders",
      "Partnership and collaboration facilitation",
      "Sponsor and exhibitor engagement",
      "Relationship building across the hospitality ecosystem",
    ],
  },
  {
    icon: <Award className="w-6 h-6 text-accent" />,
    title: "Hotelier Personality Leadership Awards",
    description:
      "Recognising hotel executives, GMs, CEOs and hospitality leaders who have demonstrated outstanding personal leadership in advancing Africa's hospitality sector.",
    imagePath: images.projectFintech,
    label: "Award Tier 1",
    detailsLabel: "Award Categories",
    ctaLabel: "Nominate now — marcom@sbfafrica.com",
    details: [
      "Hotelier of the Year – Africa",
      "Hospitality CEO Leadership Excellence Award",
      "General Manager of the Year – Luxury Hotels",
      "General Manager of the Year – Business Hotels",
      "General Manager of the Year – Boutique Hotels",
      "Emerging Hospitality Leader of the Year",
      "Women Leadership Excellence in Hospitality Award",
      "Hospitality Industry Icon Award",
      "Hospitality Entrepreneurship Leadership Award",
      "Excellence in Resort Leadership Award",
      "Excellence in Hospitality Operations Leadership",
      "Hospitality Sales & Commercial Leadership Award",
      "Sustainable Hospitality Leadership Award",
      "Hospitality Talent Development Leadership Award",
      "Regional Hospitality Leadership Excellence Award",
    ],
  },
  {
    icon: <Star className="w-6 h-6 text-accent" />,
    title: "Hotel Brand & Institutional Awards",
    description:
      "Recognising hotel brands and hospitality organisations that have demonstrated exceptional performance, innovation, and excellence across Africa's hospitality market.",
    imagePath: images.projectNetworking,
    label: "Award Tier 2",
    detailsLabel: "Award Categories",
    ctaLabel: "Nominate now — marcom@sbfafrica.com",
    details: [
      "Luxury Hotel of the Year – Africa",
      "Luxury Resort of the Year – Africa",
      "Business Hotel of the Year – Africa",
      "Boutique Hotel of the Year – Africa",
      "Eco-Resort of the Year – Africa",
      "Leading Conference & MICE Hotel – Africa",
      "Heritage Hotel of the Year",
      "Best Regional Hotel Brand",
      "Best Luxury Boutique Hotel",
      "Best Hospitality Group / Hotel Chain",
      "Best City Hotel",
      "Best Beach Resort Hotel",
      "Best Guest Experience Hotel",
      "Best Emerging Hotel Brand",
      "Best Regional Tourism Hotel",
    ],
  },
];
